name = "MinimumVarianceAnalysis"
uuid = "5a74c7d3-1edb-47ee-a7ac-bdb4b3eeab9d"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[extensions]
MVADimensionalDataExt = "DimensionalData"

[compat]
julia = "1.10"
DimensionalData = "0.29"
LinearAlgebra = "1"
PrecompileTools = "1"
StaticArrays = "1"
Unitful = "1"
